#!/bin/sh

echo "S01InitHost - defaults"

: ${HM_MODE:="NORMAL"}

echo "Checking device"
if grep -qi "BCM2835" /proc/cpuinfo; then
  echo "Detected Raspberry PI"
  : ${HM_HOST:="Raspberry Pi"}
  : ${DEVICE_GPIO_UART:="/dev_org/ttyAMA0"}
  : ${DEVICE_GPIO_RESET:="18"}
  : ${HM_LED_GREEN:=""}
  : ${HM_LED_RED:=""}
  : ${HM_LED_YELLOW:=""}
elif grep -qi "Allwinner sun8i" /proc/cpuinfo; then /* TBD check value returned by cpuinfo for Orange */
  echo "Detected Orange Pi"
  : ${HM_HOST:="Orange Pi"}
  : ${DEVICE_GPIO_UART:="/dev_org/ttyS3"}
  : ${DEVICE_GPIO_RESET:="110"}
  : ${HM_LED_GREEN:=""}
  : ${HM_LED_RED:=""}
  : ${HM_LED_YELLOW:=""}
else
  echo "Did not recognize HW $(grep Hardware /proc/cpuinfo) -> Homematic PCB adapter will not work"
  : ${HM_HOST:="Unknown"}
  : ${DEVICE_GPIO_UART:=""}
  : ${HM_HOST_GPIO_RESET:=""}
  : ${HM_LED_GREEN:=""}
  : ${HM_LED_RED:=""}
  : ${HM_LED_YELLOW:=""}
fi

: ${HM_HOST_GPIO_UART:="/dev/raw-uart"}
if [ ! -e "${HM_HOST_GPIO_UART}" ]; then
  echo -n "${HM_HOST_GPIO_UART} does not exists: "
  if [ -e "${DEVICE_GPIO_UART}" ]; then
    echo "using ${DEVICE_GPIO_UART}"
    ln -sf "${DEVICE_GPIO_UART}" "${HM_HOST_GPIO_UART}"
    HM_HOST_GPIO_UART=$DEVICE_GPIO_UART
    HM_HOST_GPIO_RESET=$DEVICE_GPIO_RESET
  else
    echo "disabling UART"
    HM_HOST_GPIO_UART=""
  fi
fi


HM_LED_GREEN_MODE1="none"
HM_LED_GREEN_MODE2="none"
HM_LED_RED_MODE1="none"
HM_LED_RED_MODE2="none"
HM_LED_YELLOW_MODE1="none"
HM_LED_YELLOW_MODE2="none"


# save all changed HM_ env variables
set | grep '^HM_' >>/var/hm_mode
#Eliminate duplicates
. /var/hm_mode
set | grep '^HM_' >/var/hm_mode

#!/bin/sh
exit 0
